### ISSUE TITLE
Remove a pasta node_modules

### ISSUE THREAD

**Issue by bruno-lombardi** [hmarsolla/hugmun_bot#3]
Creio que vc ja sabe isso, mas pode deletar a pasta node_modules e adicionar ela em um arquivo .gitignore. Assim qualquer um pode instalar os modulos com `npm install`.

**Comment by hmarsolla** [comment]
Ahhh sim, muito bom lembrar disso! Esse foi meu primeiro projeto e Node.js e eu na época não sabia muito como funcionava. Hoje já costumo colocar tudo no .gitignore já desde o início :D 
Vou dar uma alterada nesse projeto, valeu o/

**Comment by bruno-lombardi** [comment]
Legal. E hoje você já terminou o curso de Node, como está sua experiência
de trabalho? Onde você aprendeu mais ?

Em 21 de nov de 2017 16:48, "Heitor Marsolla" <notifications@github.com>
escreveu:

**Comment by hmarsolla** [comment]
Eu ainda não cheguei a terminar o curso, estou fazendo através da plataforma Udemy. Tive pouca experiência profissional com Node, ainda estou mais por conta mesmo, treinando a tecnologia.
